version: "3"
services:
  quotebook-database:
    build: ./database
	volumes:
		-./database:usr/src/app
	restart: always
    ports:
      - "3000:3000"
	depends_on:
	  - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/database
    ports:
      - "27017:27017"